---

- name: Install caching servers
  package:
    name: redis-server
    state: present
  when: redis_enabled

- name: Ensure redis only listens on localhost
  lineinfile:
    dest: /etc/redis/redis.conf
    insertafter: "^# bind 192.168.1.100 10.0.0.1"
    line: "bind 127.0.0.1"
  when: redis_enabled
  notify:
    - restart redis

- name: Install memcached
  package:
    name:
    - memcached
    - libmemcached-tools
  when: memcached_enabled



