---

- name: initial checkout of code
  git: repo={{ repository }}
       dest={{ project_home }}
       version="{{ release }}"
       force=yes
       depth=1
  # notify:
  #   - restart uwsgi
  #   - npm install
  #   - bower install
  #   - jspm install
  #   - compile sass
  #   - do collectstatic
