---
# Make sure the virtualenv is created and requirements are installed

- name: Create virtualenv directory with correct file permissions
  file: name="{{ venv }}"
        state=directory
        owner={{ application_user }}
        group={{ application_user }}
        mode=0755
  remote_user: root

- name: Create virtualenv
  pip:
    name: pip
    virtualenv: "{{ venv }}"
    virtualenv_python: python3.6

- name: Install requirements
  pip:
    chdir: "{{ project_home }}"
    virtualenv: "{{ venv }}"
    requirements: "requirements/{{ target_env }}.txt"
  notify:
    - restart uwsgi

- name: Remove old source-trick
  lineinfile: dest={{ venv }}/bin/activate state=absent line="export $(cat {{ env_file_dest }} | xargs)"

- name: Automatically export environment from file on the server itself
  lineinfile: dest={{ venv }}/bin/activate state=present line="source {{ env_file_dest_bash }}"
