---
# Make sure the virtualenv is created and requirements are installed

- name: Install requirements
  pip: virtualenv={{ venv }}
       chdir={{ project_home }}
       requirements=requirements/{{ target_env }}.txt
       virtualenv_python=python3
  # notify:
  #   - restart uwsgi
