---

- name: Update the application to the latest version
  hosts: "{{ target|default('staging') }}"
  remote_user: regex
  roles:
    - env
    - npm
    - grunt
    - django
    - supervisor
    - nginx
