---

admin_email: root@localhost

# firewall
firewall_open_ports:
  - http
  - https

# big storage (Tansip)
bigstorage: no
bigstorage_device: /dev/vdb1
bigstorage_mount_path: /mnt/bigstorage

# databases
postgresql_enabled: yes
postgresql_version: 10
postgresql_packages:
  - postgresql
  - postgresql-client
  # python bindings
  - python-dev
  - libpq-dev
  - python-psycopg2

# webservers
apache_enabled: no
nginx_enabled: yes

# cache servers
redis_enabled: yes
memcached_enabled: no

# NodeJS
nodejs_enabled: false
nodejs_version: 10

# Django
django_enabled: false
django_packages:
  - python3-dev
  - python3-setuptools
  - python3-pip
  - python-virtualenv
  # lxml depend on these
  - libxml2
  - libxml2-dev
  - libxslt1.1
  - libxslt1-dev
  # Pillow
  - swig
  - libjpeg-dev
  # weasyprint
  - libcairo2
  - libpango1.0-0
  - libgdk-pixbuf2.0-0
  - libffi-dev
  - shared-mime-info
