---

- name: Ensure mailname is set correctly
  copy:
    path: /etc/mailname
    backup: yes
    content: "{{ postfix_mydomain }}"

- name: Install postfix
  package:
    name:
    - postfix
    # - dovecot-core
    # - dovecot-imapd
    - postfix-pgsql
    - dovecot-pgsql

    # - dovecot-lmtpd

# - name: Set up the forwards
#   template:
#     src: virtual.j2
#     dest: /etc/postfix/virtual
#   notify:
#     - postmap virtual

- name: Set up the postfix config
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify:
    - reload postfix
