---

- name: Ensure mailname is set correctly
  copy:
    dest: /etc/mailname
    backup: yes
    content: "{{ postfix_mydomain }}"

- name: Install postfix
  package:
    name:
    - postfix
    - postfix-pgsql

- name: Create dir for pgsql configs
  file:
    path: /etc/postfix/pgsql
    state: directory

- name: Template out the PGSQL virtal aliases
  template:
    src: "{{ item }}.cf.j2"
    dest: "/etc/postfix/pgsql/{{ item }}.cf"
  with_items:
    - virtual_alias_domains
    - virtual_alias_map

- name: Set up the postfix config
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
#   notify:
#     - reload postfix
