---

- name: make sure the log dir exists
  file: path=/var/log/nginx/{{ prefix }} state=directory

- name: Create the nginx vhost
  template: src=vhost.j2
            dest=/etc/nginx/sites-available/{{ prefix }}.conf
            owner={{ application_user }}
            group={{ application_user }}
            mode=0644
  notify: reload nginx

- name: Enable the virtual host
  file: src=/etc/nginx/sites-available/{{ prefix }}.conf
        dest=/etc/nginx/sites-enabled/{{ prefix }}.conf
        owner={{ application_user }}
        group={{ application_user }}
        state=link
  notify: reload nginx
