---

- name: Define log format
  copy:
    src: logformat.conf
    dest: /etc/nginx/conf.d/logformat.conf
  remote_user: root

- name: make sure the log dir exists
  file:
    path: "/var/log/nginx/{{ prefix }}"
    state: directory
  remote_user: root

- name: Create the nginx vhost
  template:
    src: "{{ nginx_vhost_template }}"
    dest: /etc/nginx/sites-available/{{ prefix }}.conf
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
    mode: 0644
  remote_user: root
  notify: reload nginx

- name: Enable the virtual host
  file:
    src: /etc/nginx/sites-available/{{ prefix }}.conf
    dest: /etc/nginx/sites-enabled/{{ prefix }}.conf
    owner: "{{ application_user }}"
    group: "{{ application_user }}"
    state: link
  remote_user: root
  notify: reload nginx
