---

- name: Provisioning - install the base packages
  apt: name={{ item }} state=present
  with_items:
    - git
    - nginx
    - python3-dev
    - python3-setuptools
    - redis-server
    # lxml depend on these
    - libxml2
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev
    - swig
    - libjpeg-dev

    - python3-pip
    - python-virtualenv

    # weasyprint
    - libcairo2
    - libpango1.0-0
    - libgdk-pixbuf2.0-0
    - libffi-dev
    - shared-mime-info

# node_Release_file: https://deb.nodesource.com/node_6.x/dists/jessie/Release

- name: Add apt-key for (recent) NodeJS
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  remote_user: root

- name: Add NodeJS sources
  copy:
    src: nodesource.list
    dest: /etc/apt/sources.list.d/nodesource.list
    mode: "u=rw,g=r,o=r"
  remote_user: root

- name: Install NodeJS
  package:
    name: nodejs
    state: present
    update_cache: yes
  remote_user: root
